from .annotation_service import (
    AnnotationDocument,
    NormalizedBox,
    apply_class_changes_atomic,
    build_class_id_mapping,
    dedupe_auto_annotation_candidates,
    load_annotation_document,
    load_classes_file,
    load_pixel_boxes,
    rewrite_label_file_atomic,
    save_classes_file_atomic,
    save_pixel_boxes_atomic,
)
from .config_store import ConfigStore
from .dataset_scanner import DatasetScanner, parse_yolo_label
from .dataset_quality import (
    ClassDistribution,
    DatasetQualityReport,
    DatasetQualityScanner,
    DuplicateGroup,
    QualityFinding,
)
from .dataset_split import (
    ClassCoverage,
    ClassCoveragePolicy,
    SplitMode,
    SplitMove,
    SplitPlan,
    SplitPlanner,
    SplitPolicy,
    SplitRisk,
    SplitSample,
    compute_dataset_fingerprint,
)
from .dataset_split_executor import (
    SplitExecutionError,
    SplitExecutionResult,
    SplitExecutor,
    SplitRecoveryService,
    SplitRestoreResult,
    StaleSplitPlanError,
)
from .dataset_state import (
    DatasetSnapshot,
    ImageAnnotationState,
    ImageRecord,
    SplitSummary,
)
from .diagnostics import (
    build_diagnostic_archive,
    install_global_exception_hook,
    write_crash_report,
)
from .issues import Issue, IssueSeverity
from .model_evaluation import (
    ClassEvaluationMetrics,
    ClassMetricDelta,
    EvaluationDatasetSnapshot,
    EvaluationMetrics,
    EvaluationSession,
    MetricDelta,
    ModelComparison,
    ModelEvaluationReport,
    compare_model_reports,
    load_evaluation_session,
    save_evaluation_session,
    scan_evaluation_dataset,
)
from .paths import ProjectPaths
from .runtime_paths import RuntimePaths
from .model_registry import (
    DownloadableModel,
    MODEL_CATALOG,
    ModelDownloadCancelled,
    ModelDownloadError,
    ModelDownloadResult,
    download_model,
    get_model,
    installed_models,
    validate_model_file,
)
from .task_manager import TaskLifecycle, TaskManager, TaskStatus
from .task_protocol import (
    TASK_EVENT_PREFIX,
    TaskEvent,
    TaskEventEmitter,
    TaskEventType,
    decode_task_event,
    encode_task_event,
)
from .version import (
    DISPLAY_VERSION,
    FILE_VERSION,
    LICENSE_ID,
    PUBLISHER_NAME,
    PRODUCT_NAME,
    get_source_url,
)
from .worker_commands import WORKER_SCRIPTS, build_worker_command

__all__ = [
    "AnnotationDocument",
    "ConfigStore",
    "DatasetScanner",
    "DatasetSnapshot",
    "DISPLAY_VERSION",
    "EvaluationDatasetSnapshot",
    "EvaluationMetrics",
    "EvaluationSession",
    "FILE_VERSION",
    "DatasetQualityReport",
    "DatasetQualityScanner",
    "DuplicateGroup",
    "ClassDistribution",
    "ClassEvaluationMetrics",
    "ClassMetricDelta",
    "ClassCoveragePolicy",
    "ClassCoverage",
    "ImageAnnotationState",
    "ImageRecord",
    "Issue",
    "IssueSeverity",
    "LICENSE_ID",
    "MetricDelta",
    "ModelComparison",
    "ModelEvaluationReport",
    "NormalizedBox",
    "PUBLISHER_NAME",
    "PRODUCT_NAME",
    "ProjectPaths",
    "RuntimePaths",
    "DownloadableModel",
    "MODEL_CATALOG",
    "ModelDownloadCancelled",
    "ModelDownloadError",
    "ModelDownloadResult",
    "QualityFinding",
    "SplitSummary",
    "SplitMode",
    "SplitExecutionError",
    "SplitExecutionResult",
    "SplitExecutor",
    "SplitMove",
    "SplitPlan",
    "SplitPlanner",
    "SplitPolicy",
    "SplitRisk",
    "SplitRecoveryService",
    "SplitRestoreResult",
    "SplitSample",
    "TASK_EVENT_PREFIX",
    "TaskEvent",
    "TaskEventEmitter",
    "TaskEventType",
    "TaskLifecycle",
    "TaskManager",
    "TaskStatus",
    "StaleSplitPlanError",
    "apply_class_changes_atomic",
    "build_class_id_mapping",
    "compute_dataset_fingerprint",
    "dedupe_auto_annotation_candidates",
    "decode_task_event",
    "encode_task_event",
    "load_annotation_document",
    "load_classes_file",
    "load_pixel_boxes",
    "parse_yolo_label",
    "rewrite_label_file_atomic",
    "save_classes_file_atomic",
    "save_pixel_boxes_atomic",
    "save_evaluation_session",
    "scan_evaluation_dataset",
    "compare_model_reports",
    "load_evaluation_session",
    "download_model",
    "get_model",
    "get_source_url",
    "installed_models",
    "validate_model_file",
    "WORKER_SCRIPTS",
    "build_worker_command",
    "build_diagnostic_archive",
    "install_global_exception_hook",
    "write_crash_report",
]
